# Code Portfolio - Andrew Koren
## Subjects
* Python basics
* Numpy
* Pandas
* Matplotlib

### Python basics
Boolean examples

In [5]:
print (1 == 2)
print (1 >= 2)
print (not 1 >= 2)
print ('true' or 'False')


False
False
True
true


Falsey items
<br> None
<br> 0 (integer)
<br> 0.0 (floating-point number)
<br> '' (empty string)
<br> [] (empty list)
<br> {} (empty dictionary)
<br> () (empty tuple)

In [6]:
print ('True' or 'False')
print (not [])

cheeseburger = []

if cheeseburger:
    print (str(cheeseburger) + ' this doesn\'t run')
else:
    cheeseburger.append('wow')

if cheeseburger:
    print (str(cheeseburger) + ' this does run')
else:
    cheeseburger.append('wow')

list1 = [1, 2, 3]
list2 = [1, 2, 3]

if list1 == list2:
    print("The two lists are the same.")
else:
    print("The two lists are not the same.")


True
True
['wow'] this does run
The two lists are the same.


### Numpy

Numpy arrays can do math without being annoying. It just makes sense

In [7]:
import numpy as np
#part 1
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

result = arr1 + arr2 #other math operations will operate on all entries, etc. It just makes sense
print('p1', result)

#part 2
sub_array = arr1[1:3] #the last index in the slice isn't included, only 1 and 2 are included
print('p2', sub_array)

#part 3
arr = np.array([[1, 2, 3], [4, 5, 6]])
reshaped_arr = arr.reshape(3, 2)
transposed_arr = arr.T

print('p3','this is reshape it turns the array into a list and orders them like you read a book')
print(reshaped_arr)
print('this is transposed')
print(transposed_arr)

#part 4
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
stacked = np.hstack((arr1, arr2))  # Horizontally stack
vstacked = np.vstack((arr1, arr2))
split1,split2 = np.split(stacked, 2)      # Split into two equal parts
print('p4 \n',stacked,'\n',vstacked,'\n',split1)

p1 [5 7 9]
p2 [2 3]
p3 this is reshape it turns the array into a list and orders them like you read a book
[[1 2]
 [3 4]
 [5 6]]
this is transposed
[[1 4]
 [2 5]
 [3 6]]
p4 
 [1 2 3 4 5 6] 
 [[1 2 3]
 [4 5 6]] 
 [1 2 3]


### Pandas

Pandas is good for much its data frames, which are better for much larger data sets than np arrays

In [8]:
import pandas as pd

data = {'Name': ['Alice', 'Bob', 'Charlie'],
        'Age': [25, 30, 35]}

df = pd.DataFrame(data)
#for importing csv df = pd.read_csv('data.csv')

#df.head() gives the top
print('part1 \n',df.info())

# Selecting a column
names = df['Name']
# Selecting specific columns for rows where 'Age' is greater than 30
row1 = df.loc[df['Age'] > 30, ['Name', 'Age']]
# Selecting rows by index
row2 = df.iloc[:,1]
print('part2 \n names \n',names,'\n row 1 \n',row1,'\n row 2 \n', row2)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Name    3 non-null      object
 1   Age     3 non-null      int64 
dtypes: int64(1), object(1)
memory usage: 180.0+ bytes
part1 
 None
part2 
 names 
 0      Alice
1        Bob
2    Charlie
Name: Name, dtype: object 
 row 1 
       Name  Age
2  Charlie   35 
 row 2 
 0    25
1    30
2    35
Name: Age, dtype: int64


### Matplotlib

Honestly matplotlib.pyplot is pretty easy. Any little things to know are in snippets

<img src="https://github.com/msu-cmse-courses/cmse201-supplemental/blob/main/Day-14/solve_ivp_structure.png?raw=true" alt="solve-ivp-structure" border="0" width=1200>

## Code snippets

These don't necessarily work since they're cut from their original sources, but they've got some bits I could use

In [9]:
gdp = gdp.drop(['Country Name','Country Code','Indicator Name','Indicator Code']) #drop columns by key
gdp = gdp.dropna(axis="columns", how="all") # drop empty columns, like the last column in gdp
gdp = gdp.dropna()#how='any') # drop rows with NaNs, like Aruba and Angola
gdp.head()
gdp.keys()

# The following line is provided to help get you started, you need to decide what to use for the "x" argument
plt.axvline(np.mean(random_distribution),linewidth=2, color='b',label = "Mean")
plt.axvline(np.median(random_distribution),linewidth=2, color='r',label = "Median")
plt.legend()

alldata = np.loadtxt("michigan_pop.csv", usecols = (0,1), skiprows = 1, delimiter=',') # example for the michigan population file

Example_DataFrame = pd.DataFrame([['A',0,1,2,3],['B',4,5,6,7],['C',8,9,10,11],['D',12,13,14,15]]) #Creates an example dataframe 

plt.hist(PbBottles1,11)
plt.axvline(15, color = 'red')
plt.xlabel('Lead ppm')
plt.ylabel('Count')
plt.title('Flint the Musical')
plt.yscale('log')
#plt.grid(True)

nations = gini['name']
unemployment = unemployment.set_index('name')
unemployment = unemployment.reindex(nations)

#matplot time
fig, (ax0, ax1) = plt.subplots(ncols=2, figsize=(9, 4))
hb = ax0.hexbin(gini['value'], unemployment['value'], gridsize=20, cmap='inferno')
ax0.xlim=gini_lim
ax0.ylim=unemployment_lim
ax0.set_title("Gini Index vs Life Expectancy")
cb = fig.colorbar(hb, ax=ax0)
ax0.set_xlabel('Gini Index')
ax0.set_ylabel('Unemployment (%)')
#ax0.set_yscale('log')

import matplotlib.pyplot as plt
%matplotlib inline

plt.plot(x_data,y_data,label="X Data")
plt.xlabel("X Data")
plt.ylabel("Y Data")
plt.title("X Vs. Y Dataset")
plt.grid()

NameError: name 'gdp' is not defined

These ones actually run

In [ ]:
my_array_range = np.arange(0,10,1) # Make sure you understand how this line is different...
my_array_linspace = np.linspace(0,9,10) # ... than this line
print("Using arange I get:", my_array_range)
print("Using linspace I get:", my_array_linspace)

Using arange I get: [0 1 2 3 4 5 6 7 8 9]
Using linspace I get: [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [ ]:
Example_DataFrame = pd.DataFrame([['A',0,1,2,3],['B',4,5,6,7],['C',8,9,10,11],['D',12,13,14,15]]) #Creates an example dataframe 

Example_DataFrame.index = Example_DataFrame[0] # Reads the first column
#print(Example_DataFrame)

Example_DataFrame = Example_DataFrame.iloc[:,1:] # selects all rows and all columns, skipping the first column (index 0)
#print(Example_DataFrame)

#print('name',Example_DataFrame.index.name)
Example_DataFrame.index.name = None # This line is removing the column header for the index column
#print(Example_DataFrame)
#print(Example_DataFrame.index.name)

Example_DataFrame.columns = ['Col_1', 'Col_2', 'Col_3','Col_4'] # names the columns 'Col_n' 

print(Example_DataFrame.head())


print(Example_DataFrame['Col_1'].loc['A'])

#Index Row B with loc
print(Example_DataFrame.loc['B'])

#Index Row B with .iloc
print(Example_DataFrame.iloc[1])
#Or
#Index Row B with .iloc
print(Example_DataFrame.iloc[1,:])

   Col_1  Col_2  Col_3  Col_4
A      0      1      2      3
B      4      5      6      7
C      8      9     10     11
D     12     13     14     15
0
Col_1    4
Col_2    5
Col_3    6
Col_4    7
Name: B, dtype: int64
Col_1    4
Col_2    5
Col_3    6
Col_4    7
Name: B, dtype: int64
Col_1    4
Col_2    5
Col_3    6
Col_4    7
Name: B, dtype: int64


#### Assorted notes

In [12]:
#Linspace splits by buckets
time = np.linspace(0,10,6)
time #you always need one more bucket than you think to contain 0



array([ 0.,  2.,  4.,  6.,  8., 10.])

In [3]:
import pandas as pd

data = {'A': [1, 2, 3, 4, 5],
        'B': [10, 20, 30, 40, 50]}

df = pd.DataFrame(data)
print('0\n',df)
#1 Filtering rows where column A is greater than 2
result = df[df['A'] > 2]
print('1\n',result)
#2 Count of rows where A is greater than 2
count = (df['A'] > 2).sum()
print('2\n',count)
#3 Set column B to 0 for rows where A is less than 3
dfclone = df
dfclone.loc[df['A'] < 3, 'B'] = 0
print('3\n',dfclone)
#4 Rows where column A is not null
result = df[df['A'].notna()]
print('4\n',result)
#5 Rows where A is greater than 2 and B is less than 40
result = df[(df['A'] > 2) & (df['B'] < 40)]
print('5\n',result)

0
    A   B
0  1  10
1  2  20
2  3  30
3  4  40
4  5  50
1
    A   B
2  3  30
3  4  40
4  5  50
2
 3
3
    A   B
0  1   0
1  2   0
2  3  30
3  4  40
4  5  50
4
    A   B
0  1   0
1  2   0
2  3  30
3  4  40
4  5  50
5
    A   B
2  3  30


I don't really want to do a code portfolio but I need to to get full points. Here's some more code snippets so I can get points

board-type code

In [ ]:
# Finish this code
def onBoard(i, j, image):
    ni = image.shape[0] # number of pixels (height)
    nj = image.shape[1] # number of pixels (width)
    if i <= ni-1 and i >= 0 and j <= nj-1 and j>=0: # You need some more conditions here! 
                                         # We've checked i, but what about j?
        return True
    else:
        return False

more masking stuff

In [ ]:
# Check out the | operator.  It acts like "or" to combine two different conditions
mask_red = (beach_red < avg_red - tolerance) | (beach_red > avg_red + tolerance) 
mask_green = (beach_green < avg_green - tolerance) | (beach_green > avg_green + tolerance) 
mask_blue = (beach_blue < avg_blue - tolerance) | (beach_blue > avg_blue + tolerance) 


masking

In [ ]:
##The following code separates out the red, blue, and green components for each of the pixels in our image
red_array, green_array, blue_array = picture_array[:,:,0], picture_array[:,:,1], picture_array[:,:,2]

board-type code

In [ ]:
def fast_advance_board(game_board,firelist):
    '''
    Advances the game board quickly.
    Input: the initial game board and locations that will need updates.
    Output: the advanced game board and new update locations
    '''

    new_fire = []

    for i,j in firelist:
        #print(i,j)
        neigbors = locate_neighbors(i,j)
        
        for neighbor in neigbors:
            if onBoard(neighbor[0],neighbor[1],game_board):
                if game_board[neighbor[0],neighbor[1]] == 1:
                    game_board[neighbor[0],neighbor[1]] = 2
                    new_fire.append((neighbor[0],neighbor[1]))
        game_board[i,j] = 0
    #print(len(firelist))
    #print(len(new_fire))
    # return the new board
    return game_board, list(set(new_fire))

model of difeq equation & solution

In [ ]:
def LVnew(time, current_state, alpha, beta, delta, gamma, pcap):
    
    prey = current_state[0]
    predators = current_state[1]
    
    dprey_dt = alpha*prey*(1-prey/pcap) - beta*prey*predators
    dpredators_dt = delta*prey*predators - gamma*predators
    
    return [dprey_dt, dpredators_dt]

alpha = 1
beta = 4/3
delta = 1
gamma = 1
pcap = 4
initial_conditions = [1,.1]
time = np.linspace(0,30,1000)

result = solve_ivp(LVnew, (0,30),initial_conditions, t_eval = time, args=(alpha, beta, delta, gamma,pcap))
                        #(0,30) is time frame
prey = result.y[0,:]
predators = result.y[1,:]

basic data cleaning

In [ ]:
# put your code here
data = pd.read_csv('estimated_crimes_1979_2022.csv')
#data.head()
data_without_nan = data.dropna(subset=['state_abbr'])
data_without_nan_dropped = data_without_nan.dropna(axis=1)
data_without_nan_dropped.head()
