# Banana Camel
3000 Bananas
1000 kilometers
1 camel

In [1]:
import numpy as np

## attempt #1

In [26]:
distance = np.zeros((1001))
distance[:]

array([0., 0., 0., ..., 0., 0., 0.])

In [29]:
initial_bananas = 3000
distance[0] = initial_bananas
distance

array([3000.,    0.,    0., ...,    0.,    0.,    0.])

In [32]:
max_bananas = 1000
def camel(x1,x2, field, maxbna = max_bananas):
    newfield = field.copy()
    source_bna = field[x1]
    result_bna = field[x2]

    transfer = min(source_bna,max_bananas)
    
    newfield[x1] = source_bna - transfer
    newfield[x2] = result_bna + transfer - abs(x2-x1)
    
    return newfield

In [ ]:
def carry_all(x1,x2,field):
    newfield = field.copy()
    while newfield[x1] > 0:
        camel(x1,x2)

In [33]:
camel(0,1, distance)

array([2000.,  999.,    0., ...,    0.,    0.,    0.])

## attempt #2
The camel has a definite location, so we'll keep a track of its location

In [3]:
import numpy as np

In [18]:
camel_location = 0
camel_max = 1000
initial_bananas = 3000

board_initial = np.zeros(1001)
board_initial[0] = initial_bananas

board = np.array([board_initial])

#Example of time-step
#board2 = board_initial.copy()
#board2[1] = 69420
#
#result_board = np.concatenate((board, [board2]))
#result_board

In [70]:
def move_camel(x1,board,move_bnas = camel_max):
    newboard = board.copy()
    consume = abs(camel_location-x1)

    transfer = max(min(newboard[camel_location],move_bnas),consume)
    newboard[camel_location] -= transfer
    newboard[x1] += transfer - consume
    return newboard, x1

In [73]:
camel_location = 0
camel_max = 1000
initial_bananas = 3000

board_initial = np.zeros(1001)
board_initial[0] = initial_bananas

board = np.array([board_initial])

commands = [(1,1000),(0,0),(1,1000),(0,0),(1,1000)]

for step, i in enumerate(commands):
    location, amount = i
    newstate, camel_location = move_camel(location,board[step],amount)
    board = np.concatenate((board,[newstate]),axis=0)

print(board)




[[3000.    0.    0. ...    0.    0.    0.]
 [2000.  999.    0. ...    0.    0.    0.]
 [2000.  998.    0. ...    0.    0.    0.]
 [1000. 1997.    0. ...    0.    0.    0.]
 [1000. 1996.    0. ...    0.    0.    0.]
 [   0. 2995.    0. ...    0.    0.    0.]]


Great! Now we've got the premise down. We just need to create our algorithm

In [99]:
camel_location = 0
camel_max = 1000
initial_bananas = 3000

board_initial = np.zeros(1001)
board_initial[0] = initial_bananas

board = np.array([board_initial])

step = 0
for i in range(len(board[0])-1):
    #print(step,i,camel_location,'\n',board)        
    newstate, camel_location = move_camel(i+1,board[step],camel_max)
    board = np.concatenate((board,[newstate]),axis=0)
    step += 1
    while board[step,i] > 0:
        #print(step,i,camel_location,'\n',board)
        newstate, camel_location = move_camel(i,board[step],0)
        board = np.concatenate((board,[newstate]),axis=0)
        step += 1
        #print(step,i,camel_location,'\n',board)        
        newstate, camel_location = move_camel(i+1,board[step],camel_max)
        board = np.concatenate((board,[newstate]),axis=0)
        step += 1
        

        



In [100]:
board

array([[3000.,    0.,    0., ...,    0.,    0.,    0.],
       [2000.,  999.,    0., ...,    0.,    0.,    0.],
       [2000.,  998.,    0., ...,    0.,    0.,    0.],
       ...,
       [   0.,    0.,    0., ...,  534.,    0.,    0.],
       [   0.,    0.,    0., ...,    0.,  533.,    0.],
       [   0.,    0.,    0., ...,    0.,    0.,  532.]])

Alright, now all that's left is plotting!