### <p style="text-align: right;"> &#9989; Andrew Koren</p>

# PHY480 Homework 3


This homework contains exercises on the eigenvalue problems. There are two parts:

- tensor of inertia,
- one-dimensional quantum harmonic oscillator.

For the first part we will use the QR method that we coded ourselves in class, for the second part the NumPy functions, such as `numpy.linalg.eig`.

**There are 7 problems with the total of 37 points.**

**The deadline for the homework is Wednesday, March 19, 2025, 6:00 pm.**


In [1]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import scipy


## Eigenvalue problems

### Inertia tensor

**Problem 1 (6 points).** Consider the following geometrical shape in three dimensions: a region of space bounded by planes $x=0$, $y=0$, $z=0$ and a sphere $x^2+y^2+z^2=R^2=1$, where $x\geqslant0$, $y\geqslant0$, $z\geqslant0$ and $x^2+y^2+z^2\leqslant1$. (This is esentially $1/8$ slice of a sphere with the center at the origin.) Let this geometrical shape be filled with mass density $\rho=1$.

The tensor of inertia is a $3\times3$ symmetric matrix $I_{ij}$ whose elements are given by (here $V$ is the volume occupied by the shape, the mass density $\rho=1$ and $r^2=x^2+y^2+z^2$):

$$
I_{xx}=\int_V dV\, (r^2-x^2),
$$

for the diagonal elements (for $I_{yy}$ and $I_{zz}$ replace $x$ with $y$ and $z$, correspondingly), and

$$
I_{xy}=\int_V dV\, (-xy),
$$

for the non-diagonal elements (replace $x$ and $y$ correspondingly for the other non-diagonal elements).

Evaluate the tensor of inertia for the described shape with respect to the origin, either analytically (preferable) or numerically. (It is convenient to work in spherical coordinates.)

# Integrals:

$$
\int dV = \int_0^{2\pi} \int_0^\pi \int_0^R \rho^2 \sin \phi d\rho d\phi d\theta  \\
x = \rho \cos \theta \sin \phi \\
y = \rho \sin \theta \sin \phi \\
z = \rho \cos \phi
$$

Our bounds are less general

$$
\int_0^{\pi/2} \int_0^{\pi/2} \int_0^1
$$

In [14]:
import sympy as sm
from sympy import cos, sin

rho, theta, phi = sm.symbols('rho theta phi')
x = rho * cos(theta) * sin(phi)
y = rho * sin(theta) * sin(phi)
z = rho * cos(phi)

integrate_with_bounds = lambda integrand: sm.integrate(integrand * rho*rho * sin(phi), (rho, 0, 1), (theta, 0, sm.pi/2), (phi, 0, sm.pi/2))

display(integrate_with_bounds(rho*rho-x*x)) #same for y, z
display(integrate_with_bounds(-x*y)) #same for xz, yz


pi/15

-1/15

In [17]:
# tensor of inertia for 1/8 slice of a filled sphere
# REPLACE 0s WITH PROPER VALUES
from numpy import pi

Itensor = np.array( [   \
    [ pi, -1, -1], \
    [ -1, pi, -1], \
    [ -1, -1, pi]  \
])/15

Itensor

array([[ 0.20943951, -0.06666667, -0.06666667],
       [-0.06666667,  0.20943951, -0.06666667],
       [-0.06666667, -0.06666667,  0.20943951]])

**Problem 2 (5 points).** Use the QR method we considered in class to diagonalize the tensor of inertia and find its eigenvalues -- the principal moments of intertia. Sort the eigenvalues in ascending order. Check against `numpy.linalg.eig` calculation.

**Note:** For this rigid body you may expect degenerate eigenvalues.

Finding eigenvalues with QR:
1. Symmetric matrix
2. QR = A
3. A' = RQ
4. repeat, diagonal is eigenvalues

$A' = Q^T A Q$ is the same as 3.

In [18]:
def qrdec(A):
    n = A.shape[0]
    Ap = np.copy(A)
    Q = np.zeros((n,n))
    R = np.zeros((n,n))
    for j in range(n):
        for i in range(j):
            R[i,j] = Q[:,i]@A[:,j]
            Ap[:,j] -= R[i,j]*Q[:,i]

        R[j,j] = np.linalg.norm(Ap[:,j])
        Q[:,j] = Ap[:,j]/R[j,j]
    return Q, R

def eigenvalues_with_QR( A, max_iter=100, print_iter=False ):

    # store a copy so that the original matrix is not disturbed
    Ak = A.copy()
    for i in range(max_iter):
        eigenvals = np.sort(np.diagonal(Ak))

        Q, R = qrdec(Ak)
        Ak = R@Q # also Q.T@Ak@Q
        
        if all(eigenvals == np.sort(np.diagonal(Ak))): #convergence to machine accuracy
            return 0, eigenvals
        
        if print_iter:
            print(i, eigenvals)

    return 1, eigenvals # did not reach machine accuracy

In [ ]:
success, eigenvals = eigenvalues_with_QR(Itensor) # repeated eigenvalue, makes sense
print(eigenvals)
print(np.sort(np.linalg.eig(Itensor)[0]))

[0.07610618 0.27610618 0.27610618]
[0.07610618 0.27610618 0.27610618]


: 

**Problem 3 (5 points).** Using the inverse power iteration method we considered in class, find the eigenvectors corresponding to the eigenvalues. Make sure the eigenvectors are normalized to have unit length. Check against `numpy.linalg.eig`.


In [ ]:


def invpower_method( A, sigma=0, max_iter=100 ):
    
    # read off dimensions
    n = A.shape[0]
    # prepare the inverse for the power iteration method
    B = mat_inverse( A - sigma*np.eye( n ) )
    kappa, Bvec = power_method(B) #A and B have the same eigenvectors
    eigenvalue = sigma + 1/kappa

    return eigenvalue, Bvec

**Problem 4 (5 points).** Eigenvectors corresponding to a degenerate eigenvalue may not be orthogonal. In fact, the inverse power iteration method may converge to the same eigenvector for degenerate eigenvalues. If some eigenvalues in this problem are degenerate, you can still _choose_ their eigenvectors to be orthogonal. Based on the eigenvectors computed by the QR method, build a set of three mutually orthogonal vectors. They will represent the _principal axes_ of the tensor of inertia. Demonstrate that the chosen vectors are orthonormal and that in the coordinate system where these vectors coincide with $x$, $y$, $z$ directions the tensor of inertia is diagonal.

In [ ]:
# YOUR CODE HERE


###  Quantum harmonic oscillator

In general, a quantum-mechanical system can be described by a _wave function_ $\psi(\vec{r},t)$ that satisfies a time-dependent Schrodinger equation:

$$
i\hbar \frac{\partial \psi}{\partial t}=\hat H\psi,
$$

where $\hat H$ is the Hamiltonian (operator) and we set $\hbar$ to 1 for simplicity. If the Hamiltonian does not depend on time $t$ explicitly, the problem can be reduced to a _time-independent_ Schrodinger equation:

$$
\hat H\psi =E\psi
$$

that describes _stationary states_. Supplemented with some boundary conditions the above equation forms an eigenvalue problem for the operator $\hat H$. Its solution gives us the energy levels $E$ (eigenvalues) that the system can occupy and the wave functions or state vectors $\psi(\vec{r})$ (eigenvectors). In this formulation this is an operator eigenvalue problem. It can be reduced to a matrix eigenvalue problem.

The Hamiltonian is $\hat H=\hat T + \hat V$, where $\hat T$ is the kinetic energy and $\hat V$ potential energy operators. We can simplify the problem by considering a single degree of freedom in one dimension with a unit mass $m=1$. Then

$$
\hat T = - \frac{1}{2}\,\frac{d^2}{dx^2}.
$$

For the potential energy part, consider a harmonic oscillator potential (the frequency $\omega=1$ for simplicity):

$$
\hat V = \frac{1}{2}x^2.
$$

As this potential only supports bound states, a reasonable boundary condition is the wave function vanishing at infinity. All together, we have the following operator eigenvalue problem:

$$
\left(- \frac{1}{2}\,\frac{d^2}{dx^2}+\frac{1}{2}x^2\right)\psi(x)=E\psi(x),
$$

$$
\psi(x \to\pm\infty)\to0.
$$


**Problem 5 (4 points).** Let us turn the one-dimensional operator eigenvalue problem into a matrix eigenvalue problem. First, let us restrict the range of $x$ to $-x_{max}\leqslant x \leqslant x_{max}$ (where $x_{max}$ is obviously chosen to be positive). Let $N$ (strictly even) be the number of intervals to which we divide the range of $x$. The size of the interval in that case is

$$
\Delta x = \frac{2 x_{max}}{N}.
$$

The total number of points at which we are going to find the solution is $N+1$. (Example: $x_{max}=2$, $N=4$, then $\Delta x = 1$ and the active points are $x=-2,-1,0,1,2$.) Choosing $N$ to be even simply means that 0 is included in the point set. To incorporate the boundary conditions, we set $\psi(x)=0$ for any $|x|>x_{max}$. Then the solution to the discrete problem is a vector of $N+1$ entries -- aproximation to $\psi(x)$ at the discrete set of $N+1$ points $x_i$ that we number in 0-based counting $i=0,1,\dots,N$. Then, we have a matrix eigenvalue problem of the form:

$$
\sum_{j=0}^{N}H_{ij}\psi_j = E\psi_i,
$$

where $H_{ij}$ approximates the continuous $\hat H$ shown above.

Recall that we discussed a finite-difference approximation to the second derivative of a function at point $i$ that involves also values at points $i-1$ and $i+1$. Write down a finite-difference approximation that together with the potential energy term gives $H_{ij}$. You should produce a tridiagonal matrix (i.e. the only non-zero entries are on the main diagonal, and the diagonals above and below). Complete the function below that produces $H_{ij}$. (Think how to properly use the boundary conditions for the first and last row of $H_{ij}$.)

In [ ]:
# make the Hamiltonian matrix
# Input:
# N -- number of intervals, always even
# xmax -- bound on the x-range
# Output:
# the Hamiltonian matrix (N+1)x(N+1), should be tridiagonal
def make_H( N=10, xmax=3 ):
    
    H = np.zeros( (N+1,N+1) )
    if N%2 != 0: # N must be even
        return H

    # ....
    
    return H


**Problem 6 (5 points).** In this part of the exercise we use `numpy.linalg.eig`, since it is much faster than our QR method. (As many NumPy subroutines actually call C or Fortran libraries, they are not written in Python.)
Find the eigenvalues and eigenvectors of the Hamiltonian matrix $H_{ij}$. The eigenvalues and corresponding eigenvectors may be in some random order and the eigenvectors may have a random sign. Apply the following two transformations:

- sort the eigenvalues (and eigenvectors) in the ascending order,
- flip the sign of the eigenvector if needed, so that for all eigenvectors the approach $x\to x_{max}$ is from _above_.

Print out a few low-lying eigenvalues and plot the corresponding eigenvectors. Do they match your expectations? How well the theoretical values are reproduced?

In [ ]:
# number of eigenvectors to plot
Ne = 3

# experiment with different pairs of (xmax,N), starting with low values,
# for example, start with xmax=3, try N=10, 20, 50,
# increase xmax to 4,5 and higher and try different N starting from low values
# (work with combinations that keep dx=2*xmax/N less than 1)
xmax = 3
N = 10

H = make_H( N, xmax )

# YOUR CODE HERE


**Problem 7 (7 points).** To compare with the exact solution to the one-dimensional quantum harmonic oscillator problem the state vectors (eigenvectors of $H_{ij}$ that you found) need to be properly normalized. Namely, the normalization condition is

$$
\int dx |\psi(x)|^2=1.
$$

Use a numerical integration scheme to properly normalize the eigenvectors for the low-lying states you found in the previous problem. Plot the normalized eigenvectors together with the exact solutions.

**Note:** The exact solution is given in terms of the Hermite polynomials. Consult the relevant literature on quantum mechanics (or Wikipedia).

In [ ]:
# YOUR CODE HERE


&#169; Copyright 2025,  Michigan State University Board of Trustees